In [1]:
import numpy

In [2]:
list = ['ben', 2, {'this key':[1, 'cat']}, [4, 'orange']]
list

['ben', 2, {'this key': [1, 'cat']}, [4, 'orange']]

In [3]:
vec = numpy.array([3, 4, 9])
vec

array([3, 4, 9])

vector operations like element-wise division work (unlike lists)

In [4]:
vec/2

array([1.5, 2. , 4.5])

an array of two dimensions is a matrix

In [5]:
b = numpy.array([[1,2,3],
                 [4,5,6]])    # Create a rank 2 array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
print(b.shape)                     # Prints "(2, 3)"

(2, 3)


Elements of the matrix are accessed by [row, column] indices starting from 0

In [7]:
print(b[0, 0], b[0, 1], 
      b[1, 0])   # Prints "1 2 4"

1 2 4
